# Generated by Django 4.2.6 on 2023-10-19 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField()),
                ('posted_before', models.TextField()),
                ('description', models.TextField()),
                ('connects_required', models.PositiveIntegerField()),
                ('connects_available', models.PositiveIntegerField()),
                ('client_country', models.CharField(max_length=100)),
                ('application_page_url', models.URLField()),
                ('client_properties', models.TextField()),
                ('gpt_response', models.TextField(blank=True, null=True)),
                ('gpt_answer', models.TextField(blank=True, null=True)),
                ('scrape_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape_runs.scraperun')),
            ],
        ),
    ]
