# Generated by Django 4.2.6 on 2023-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingqualifier',
            name='status',
            field=models.CharField(default='Not_Applied', max_length=20),
        ),
    ]
