# Generated by Django 4.2.6 on 2023-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_runs', '0002_jobpostingqualifier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingqualifier',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingqualifier',
            name='application_page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingqualifier',
            name='client_properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingqualifier',
            name='connects_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingqualifier',
            name='connects_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingqualifier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingqualifier',
            name='posted_before',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostingqualifier',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
