# Generated by Django 4.2.6 on 2023-11-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_runs', '0003_jobpostingqualifier_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperun',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
